server:
  port: 9999

spring:
  application:
    name: 'ntt-config-server'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/STEFFY2820/ntt-config-repo
          search-paths: '{application}'

encrypt:
  key: my-strong-secret-key
